# Railway configuration for multi-service app (Backend + Frontend)

[services.backend]
path = "plantpick-backend"
build = "pip install -r requirements.txt"
start = "uvicorn app.main:app --host 0.0.0.0 --port 8000"

[services.frontend]
path = "plantpick-frontend"
build = "npm install && npm run build"
start = "npm run preview -- --host 0.0.0.0 --port 4173"